version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: cinema
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty334455
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - backend

  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - ./mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - backend

networks:
  backend:
    driver: bridge
